# -*- coding: utf-8 -*-
"""get_aaseq_uniprot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZOZVKfyJ2-2ETaheFNTenQHtNZF_E45

## Use of Uniprot API to retrieve protein sequences

The API is built with Python

Submit the job with the sbatch command
"""

#!/bin/bash
#SBATCH --job-name=job_name
#SBATCH --partition=SP2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=24042
#SBATCH --mail-type=BEGING,END
#SBATCH --mail-user= e-mail

module load Miniconda/3

python - <<EOF

import sys
import json
import requests
from prettytable import PrettyTable

#Documentation: https://www.uniprot.org/help/api
WEBSITE_API = "https://rest.uniprot.org/"

def get_aaseq(gene):
  r = requests.get(f'{WEBSITE_API}/uniprotkb/stream?query={gene} AND (taxonomy_id:2)&format=fasta')
  with open(f"{gene}.fasta", "w") as arquivo:
      arquivo.write(r.text)


gene_list = ['gene1', 'gene2', ...]

# my_gene_list = ['CpsK', 'Alpha-2,3-N-acetylneuraminyltransferase', 'KpsM', 'KpsT',
             # 'KpsC', 'KpsD', 'KpsE', 'KpsF', 'KpsS', 'Lic3A', 'Lic3B', 'NeuS',
             # 'N-acylneuraminate cytidylyltransferase', 'NeuB', 'NeuC', 'NeuD',
             # 'NeuE', 'NeuO', 'CMP-N-acetylneuraminate-beta-galactosamide-alpha-2,3-sialyltransferase',
             # 'NagA', 'NagB', 'N-acetylneuraminate-lyase', 'Putative N-acetylmannosamine-6-phosphate-2-epimerase'
             # 'nanK', 'nanQ', 'N-acylglucosamine-2-epimerase', 'NanU', 'NanO','NanC','NanT', 'NanM', 'OmpC',
             # 'OmpF', 'SatA', 'SatB', 'SatC', 'SatD', 'SiaP',
             # 'SiaQ', 'SiaT', 'SiaM', 'Sialate O-acetylesterase', 'nagZ', 'NanH',
             # 'NanB', 'NanR']

for i in gene_list:
  get_aaseq(i)

EOF